### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by jameskleung** [vsevolodnedora/PyBlastAfterglowMag#1]
Hey there,

I'm trying to implement the code in some of my work, and in the installation process noticed some minor problems (related to the python wrapper).

First, `tqdm` I think should be in the requirements.txt (otherwise the package does not run).

Second, in `id_tools.py` there seems to be some development relics related to the `rebin` module/functions - it is not imported properly in the script.

Thanks for the hard work in putting this all together!

**Comment by vsevolodnedora** [comment]
Hello. Thank you for your interest in the project and for your suggestions. The following was addressed:

- tqdm was added to the requirements.txt 
- unused code related to paths of rebin.py was removed from id_tools.py

Your suggestions help us improve the codebase. Thank you.
