### ISSUE TITLE
error when running code/notebook outside repository location

### ISSUE THREAD

**Issue by jameskleung** [vsevolodnedora/PyBlastAfterglowMag#2]
There seems to be a problem when running the code in a working directory outside the repository.

For example, when I run the following code from the example notebook `tophat_jet.ipynb` in a working directory outside the repository, I get an error.

```
working_dir = os.getcwd() + '/tmp/' # default working directory

# run the code and get the instance of a python interfact to the code intput/output 
pba_run = run_grb(
    working_dir=working_dir, # directory to save/load from simulation data
    P=P,                     # all parameters 
    run=True,                # run code itself (if False, it will try to load results)
    path_to_cpp="{path_to_software}/PyBlastAfterglowMag/src/pba.out", # absolute path to the C++ executable of the code
    loglevel="err",         # logging level of the code (info or err)
    process_skymaps=False   # process unstractured sky maps. Only useed if `do_skymap = yes`
)
clear_output(wait=False)
```

The error I get is as follows:

```
{current_working_directory}/tmp/
 mom=599.999 Gamma=600 beta=0.999999

blastwave/../microphysics/common.h:28 EBL data file not found: {current_working_directory}/PyBlastAfterglowMag/data/EBL/Franceschini18/table.h5
```

I have specified the correct `path_to_cpp` (I have not moved it from the repository location after compiling), but the code error seems to assume a path based on my current working directory when looking for table.h5 instead (and of course the table it needs is not located there). Please let me know if you need more information.

**Comment by vsevolodnedora** [comment]
Hello. Thank you for your continuous interest in the project and your suggestions. The following was addressed:

## Bug Status

- Confirmed

## Fixes and modifications

- `run_grb()` function in `wrappers.py` now infers the location of the EBL file using `path_to_cpp` (required variable) as the EBL table is expected to be located in the source code repository by default. Note, a user can still path their orn `ebl_tbl_fpath` in the P['grb']['ebl_tbl_fpath'] into `run_grb()` and it will override the default option. 

Your suggestions help us improve the codebase. Thank you.
